### ISSUE TITLE
On the Mentor Details and Mentee Details pages, split feedback form and details since both of them are on the same page

### ISSUE THREAD

**Issue by Nikita1710** [Nikita1710/ANUFifty50-Online-Mentoring-Platform#108]
Let the mentor and mentee details be on that page and remove feedback form and put it as an option in the dropdown menu of the 'Me' tab in the navbar

**Comment by yayalu** [comment]
Do you mean
1. Put feedback on one page, and ratings on another, and keep the mentor details separate as well (i.e. create 3 separate html pages) 
OR
2. Put feedback on one page, and ratings + mentor details on another (i.e. maintain the 2 separate html pages)???
Might need to clarify this.

**Comment by Nikita1710** [comment]
@yayalu We need to separate the Feedback form and the Mentor/Mentee details. Currently they are on the same page. Two ways to do this are:
1. Make two separate HTML pages, one for each
2. Let the Mentor/Mentee details page be where it is and move the Feedback Form to the Me Tab in the navbar as in make it an option in the dropdown menu of the Me tab
![image](https://user-images.githubusercontent.com/13196868/30855491-8f148f70-a2f8-11e7-9a58-c25b39475795.png)
I have attached a screenshot for reference for option 2
