### ISSUE TITLE
Fix the carousel at the frontend for displaying news and events

### ISSUE THREAD

**Issue by Nikita1710** [Nikita1710/ANUFifty50-Online-Mentoring-Platform#12]

**Comment by tetris12367** [comment]
Should we remove the carousel altogther because it isn't really needed???

**Comment by Nikita1710** [comment]
+1 for removing it
We can probably replace it with Fifty50's twitter or instagram feed

**Comment by Nikita1710** [comment]
@Robwhit @tetris12367 What do you both think?

**Comment by Nikita1710** [comment]
A new issue has been created for removing the carousel and replacing it with something else
