### ISSUE TITLE
Move feedback form from My Mentor to one of the other pages.

### ISSUE THREAD

**Issue by alvisyin** [Nikita1710/ANUFifty50-Online-Mentoring-Platform#30]
From the user testing conducted this week, users said it is more appropriate to integrate the feedback form to one of the other pages. Also see issue #27.

**Comment by yayalu** [comment]
Where?

**Comment by alvisyin** [comment]
Nikil has add the mentor details on top of the rating form. I guess this issue can be closed. What does anyone think?

**Comment by alvisyin** [comment]
Maybe make a dropdown in My Mentor which contains the details about the mentor and the feedback form
