### ISSUE TITLE
Increase font size of answers in FAQ page.

### ISSUE THREAD

**Issue by alvisyin** [Nikita1710/ANUFifty50-Online-Mentoring-Platform#38]

**Comment by yayalu** [comment]
Pulled and the font size is still small?

**Comment by alvisyin** [comment]
How large do you want the font size to be?

**Comment by Nikita1710** [comment]
Make the font readable I guess. Maybe try and match to the font size on other pages

**Comment by alvisyin** [comment]
Sure.
