### ISSUE TITLE
Update resources.html to point to actual resources on university life, fifty50 and mental health

### ISSUE THREAD

**Issue by Nikita1710** [Nikita1710/ANUFifty50-Online-Mentoring-Platform#7]
Also update the resources on the homepage to point to actual links

**Comment by Nikita1710** [comment]
Link mental health resources to this page: http://www.anu.edu.au/students/health-wellbeing/mental-health

**Comment by Nikita1710** [comment]
@alvisyin @yayalu

**Comment by Nikita1710** [comment]
Link university life to this page: http://www.anu.edu.au/students/communities-events

**Comment by alvisyin** [comment]
The links are not correct.
