### ISSUE TITLE
Handover Document List

### ISSUE THREAD

**Issue by tetris12367** [Nikita1710/ANUFifty50-Online-Mentoring-Platform#72]
Create a document that lists what things the team will handover to ANUFifty50 and what the handover documentation will include.

**Comment by tetris12367** [comment]
https://docs.google.com/document/d/1BvC1d2qDKFlLqi-QXFdXMEKSw6MmzRhLnwTORZ9Lwuc/edit#heading=h.ih64dvpf2jm0  -- Done

**Comment by Nikita1710** [comment]
The list is now done but we need to work on the items in that list
It can be found in this folder: https://drive.google.com/drive/folders/0Bw7MUyh12MoYdmhWWDlEbnlMa2M
