### ISSUE TITLE
Remove the Carousel from the Digest page (127.0.0.1:8000/profile) and replace it with Fifty50's social media

### ISSUE THREAD

**Issue by Nikita1710** [Nikita1710/ANUFifty50-Online-Mentoring-Platform#98]
Get rid of the carousel and instead add Fifty50's Twitter, Facebook and Instagram feed on there in a summarised form

**Comment by yayalu** [comment]
FYI can't add instagram feed on there since ANUFifty50 hasn't given permission for the plugin site to make it public.
